title: TRIAGE³ Framework
description: A 3-dimensional, data-driven method for optimizing Security Operations Center (SOC) signals
baseurl: "/triage-cubed"
url: "https://Blackbird2Raven.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore

# Collections
collections:
  resources:
    output: true
    permalink: /resources/:path/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "resource" 